spring:
   zipkin:
     enabled: true
     # zipkkin dashboard的地址：通过真实IP地址访问
     base-url: http://localhost:9411/
     #flush-interval: 1 #flush间隔，默认是1秒
     #spring.zipkin.compression.enabled: true #默认是false。可以在配置文件中开启压缩，这样在发送给zipkin server之前会先把数据进行压缩
     #spring.zipkin.service.name: service1 #默认的service name是读取spring.application.name的值，你可以通过以下属性来覆盖默认策略定义想要的service name
     #spring.zipkin.locator.discovery.enabled: true #可以支持通过服务发现来定位host name

     # 通过cloud-dashboard-zipkin注册到注册中心的服务名称访问，本版本(spring-cloud-sleuth-core-1.2.5.RELEASE)不支持，需要从spring-cloud-sleuth-core-1.3.0.RELEASE开始支持这个功能
     # 配置如下：
     # baseUrl: http://cloud-dashboard-zipkin/
   sleuth:
     sampler:
       #  默认值为0.1f，现在为了测试设置100%采集
       probability: 1.0